### ISSUE TITLE
Unable to 'go get' versions after v0.1.0

### ISSUE THREAD

**Issue by eay** [florianl/go-conntrack#25]
In might be my go mod skills are deficient, but
$ go list -m -versions github.com/florianl/go-conntrack
github.com/florianl/go-conntrack v0.1.0
$ git tag
v0.1.0
v2.0.0
v3.0.0

but I can't build with v3.0.0.
$ mkdir new
$ cd new
$ cp ~/git/go-conntrack/example_DumpCPUStats_test.go d.go
$ go mod init
$ go build d.go
go: finding module for package github.com/florianl/go-conntrack
go: found github.com/florianl/go-conntrack in github.com/florianl/go-conntrack v0.1.0
# github.com/florianl/go-conntrack
../../pkg/mod/github.com/florianl/go-conntrack@v0.1.0/conntrack_nonlinux.go:55:9: undefined: extractAttributes

Edit d.go to         ct "github.com/florianl/go-conntrack/v3"
$ go build d.go
go: finding module for package github.com/florianl/go-conntrack/v3
d.go:6:2: module github.com/florianl/go-conntrack@latest found (v0.1.0), but does not contain package github.com/florianl/go-conntrack/v3

Any ideas?
